bot:
  message:
    response:
      start: "Бот для учёта финансов\n\nДобавить расход: 250 такси\nСегодняшняя статистика: /today\nЗа текущий месяц: /month\nПоследние внесённые расходы: /expenses\nКатегории трат: /categories"
      delete: "Удалил"
      categories: "Категории трат:\n\n* "
      unknown: "Я не знаю такой команды :("
    error:
      unknown: "Произошла неизвестная ошибка."

db:
  type: postgres
  host: postgres
  port: 5432
  name: finance_bot
  user: lazybear
  migrations_path: "file://migrations/postgres"

logger:
  level: info
  file: develop.log
